# fly.toml app configuration file generated for garshi-zero on 2025-06-24T20:34:11-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'garshi-zero'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
